name: TAB-Placeholders
version: 1.0.0
main: io.github.tanguygab.tabplaceholders.TABPlaceholders
api-version: 1.13
authors: [ NEZNAMY, Tanguygab ]
description: Adds some event-based PAPI placeholders to TAB
depend: [TAB]
softdepend: [Marriage,Essentials,NotQuests]
